name: build

permissions: write-all

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install
        run: yarn

      - name: Check Version
        id: check
        run: |
          OUTPUT=$(node index.js)
          echo "output=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Clone React
        if: ${{ steps.check.outputs.output != '' }}
        run: git clone https://github.com/freexiaochuan/react.git
      
      - name: Build
        if: ${{ steps.check.outputs.output != '' }}
        run: |
          cd react
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add github https://github.com/facebook/react.git
          git fetch --quiet github
          git rebase --quiet ${{ steps.check.outputs.output }}
          git log -n 3 --decorate

          yarn
          node mybuild/build.js
          ls -R dist

          cd ..
          cp -r ./react/dist ./

      - name: publish
        if: ${{ steps.check.outputs.output != '' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add package.json
          git add dist
          git commit -m 'update'
          git push

          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Test
        run: |
          yarn test