name: build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Clone React
        run: git clone https://github.com/freexiaochuan/react.git
      
      - run: ls react
      - name: Build
        run: |
          cd react
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add github https://github.com/facebook/react.git
          git fetch github
          git rebase github/main
          git log

          yarn
          node mybuild/build.js
          ls -R dist

      # - name: publish
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      #     yarn publish --non-interactive
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}